import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import client from "@/apollo/client";
import { PoolsDocument, PoolsQuery } from "@/gql/generated/graphql";

export async function getServerSideProps() {
  console.log("getServerSideProps");
  const { data } = await client.query<PoolsQuery>({
    query: PoolsDocument,
    variables: {
      first: 3,
    },
  });

  console.log(data.pools);

  return {
    props: {
      pools: data.pools,
    },
  };
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}></div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
      </main>
    </>
  );
}
